// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHMPwIxKAuyXszzumzuCFQxlp3OLTgGw',
    appId: '1:280771980898:web:b9657090f4adb28e58eb3b',
    messagingSenderId: '280771980898',
    projectId: 'splitz-96afb',
    authDomain: 'splitz-96afb.firebaseapp.com',
    storageBucket: 'splitz-96afb.firebasestorage.app',
    measurementId: 'G-CXE3X4NF72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtZSnGQnU0B2XU22GEb-iXlPNQWQ_nEk',
    appId: '1:280771980898:android:f37fb06fb8bc623058eb3b',
    messagingSenderId: '280771980898',
    projectId: 'splitz-96afb',
    storageBucket: 'splitz-96afb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOeJPsSbx-wlypw6nixef8LVJfJiIMkc',
    appId: '1:280771980898:ios:8c471dd8a01b3ccd58eb3b',
    messagingSenderId: '280771980898',
    projectId: 'splitz-96afb',
    storageBucket: 'splitz-96afb.firebasestorage.app',
    iosBundleId: 'com.example.splitz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOeJPsSbx-wlypw6nixef8LVJfJiIMkc',
    appId: '1:280771980898:ios:8c471dd8a01b3ccd58eb3b',
    messagingSenderId: '280771980898',
    projectId: 'splitz-96afb',
    storageBucket: 'splitz-96afb.firebasestorage.app',
    iosBundleId: 'com.example.splitz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUHMPwIxKAuyXszzumzuCFQxlp3OLTgGw',
    appId: '1:280771980898:web:a4c61f6d5102db0d58eb3b',
    messagingSenderId: '280771980898',
    projectId: 'splitz-96afb',
    authDomain: 'splitz-96afb.firebaseapp.com',
    storageBucket: 'splitz-96afb.firebasestorage.app',
    measurementId: 'G-C9ZLRNKLX4',
  );

}